blank_issues_enabled: false
contact_links:
  - name: Please submit to haozi-team/panel (请提交至 haozi-team/panel)
    url: https://github.com/haozi-team/panel/issues/new/choose
    about: This repository does not accept issues submissions (本仓库不接受 Issues 提交)