name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Build
        run: |
          cp .env.production .env
          cp settings/proxy-config.ts.example settings/proxy-config.ts
          pnpm dev &
          sleep 10
          kill %1
          pnpm build
          zip -r dist.zip dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.zip
